# Generated by Django 3.1.5 on 2022-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='mysite/images/')),
            ],
        ),
    ]
