# Generated by Django 3.1.5 on 2022-02-10 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20220209_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='language',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
